import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import { useEffect, useRef, useState } from 'react'
import { getData, postData, deleteUser } from '../helpers'
import Form from 'react-bootstrap/Form';
import InputGroup from 'react-bootstrap/InputGroup';
import bcrytp from 'bcryptjs'
import '../database/config/config'
import Swal from 'sweetalert2'
import MyNav from 'components/Nav'
import MyUsers from 'components/MyUsers';
import { CardGroup } from 'react-bootstrap';
import dbConnect from 'database/config/config'
import Register from 'components/Register';
import Login from 'components/Login';
import Footer from 'components/Footer'
export default function Home() {
  
  const [usuarios, setUsuarios] = useState([])

  const deleteUsuario = (id) => {
    deleteUser(id);
    Swal.fire(
      'Se eliminó el usuario!',
      `${id}`,
      'success'
    )
  }
 
  useEffect(() => {
    getData().then(({ data }) => {
      console.log(data);
      setUsuarios(data);
    })
    if (usuarios != undefined) {
      console.log('hay');
    }


  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Edu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <MyNav/>
      </header>
      <main className={styles.main}>
        <h1 className="text-center text-white bg-primary p-2"  >
          Escuela Digital Arg te da la bienvenida
        </h1>
        <p className={styles.description} >
          Escuela dedicada a las personas que quieren hacer un cambio es su vida {' '}
          <code className={styles.code}>const changeMyLife</code>
        </p>
        <div className={styles.grid}>
        <div className={styles.card}>
            <h3>Html</h3>
            <img src="./html.png" alt="" width={'150px'}/>
          </div>
          <div className={styles.card}>
            <h3>Css</h3>
            <img src="./css.png" alt="" width={'150px'} />
          </div>
          <div className={styles.card}>
          <h3>Javascript</h3>
          <img src="./js.png" alt="" width={'150px'}/>
          </div>
        </div>
        <div className={styles.grid}>
        <Register usuarios={usuarios} postData={postData} />
        </div>
        <div className={styles.grid}>
         
          <CardGroup>
            <MyUsers usuarios={usuarios} deleteUsuario={deleteUsuario} />
          </CardGroup>

    
          
        </div>
        <Login/>
      </main>
      <Footer/>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

// export async function getServerSideProps() {
//   await dbConnect()

//   /* find all the data in our database */
//   const result = await users.find({})
//   const Users = result.map((doc) => {
//     const user = doc.toObject()
//     user._id = user._id.toString()
//     return user
//   })

//   return { props: { Users: Users } }
// }